version: '3.8'

services:
  sqltestserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqltestserver
    platform: linux/amd64/v8  
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlservertestdata:/var/opt/mssql

volumes:
  sqlservertestdata:
    driver: local